### PR TITLE
Add support for macOS.

### PR DESCRIPTION
**Pull request by Steveice10**
Adds support for macOS builds, both for x64 and arm64 systems. I've tested this myself and can successfully dump PS3 discs using a USB blu-ray drive.

Some notes:
* Renamed the Linux build configuration to Unix, as general Unix-like systems can share the same configuration fine.
* `TryGetGlyphTypeface` was always returning true for the Segoe fonts, but yielding fallback fonts with all the symbols missing, so I had to disable it for macOS. Not sure if there's a better way to make sure it returns the right fonts.
* Had to disable `ExtendClientAreaToDecorationsHint` for macOS since the top bar layout does not work with macOS system decorations. Should end up similar to what the Linux builds look like.

### CODE REVIEW

**Comment by 13xforever** [comment]
That's neat, but I have some reservations:
1. I do not have access to Mac or even macOS VM, this is the main reason mac build isn't a thing yet
2.  I take issues with using external utilities and parsing text output from them. For one, I have no idea if different locales will change the output and if you need to set something like `LC_LANG` similar to Linux. And considering you're already not using the output as is, why not simply enumerate `/dev/rdisk` devices?
3. Some partial code is specific for Linux, and it depends on build configurations, so idk if renaming Linux build to Unix is warranted instead of having a new separate configuration for macOS
4. There's no support for any sort of event system to detect disc mount/unmount (for accidental ejects etc), and current implementation will shit the bed if you accidentally hit the eject button during dump, which is not ideal
5. I have zero experience with macOS security model and executable distribution in modern systems, and if it will run as is or if it requires system changes/signing to work properly on vanilla unmodified installation

**Comment by Steveice10** [comment]
2. The utility is included with macOS and is the only way I am aware of to enumerate disc drives; we can’t just look at rdisk devices as you suggest because they can be any type of storage medium. Is there a reason this is particularly worse than how Linux parses text from a proc location?

3. Okay, I can do that.

4. Is this something that exists for Windows/Linux? I can take a look at that if so and see if it’s possible on macOS.

5. It runs fine, the user may just have to allow it to run via their settings first.

**Comment by 13xforever** [comment]
1. Yes, `proc` is a kernel device/filesystem, so the interface is guaranteed to be stable and non-localizable (i.e. specifically for machine consumption).

4. Yes, Windows has several mechanisms (window messages / wmi), Linux right now is kinda a crutch, but I plan to do proper dbus events at some point

**Comment by Steveice10** [comment]
Okay, have addressed the following points:
2. Moved to using IOKit APIs to enumerate and find blu-ray drives.
3. Separated back into Linux and MacOS targets, plus fixed up the platform defines so we can have platform code for each OS.
4. Added support for disk events using the Disk Arbitration API.

**Comment by 13xforever** [comment]
I pushed some changes:
* use LibraryImport instead of old DllImport in MacOS utils
* clean up the usage of SupportedOSPlatform attributes (lowercase official RIDs)
* reuse StringBuilder in Dumper
* revert and update csproj changes to define platform-specific constants to make Rider happy (Linux build is still semi-broken)
* reverted changes in MainViewModel, these changes do not concern this PR
* change MainWindow.xaml binding for client decorations (Linux doesn't use them as well)
* fixed CoreFoundation namespace conflict (new .net8 defines)
* removed custom delegate and local variable declarations for event handlers (needs testing just to be sure)
* moved macos build in a separate publish script as it requires macos and xcode tools (there's no cross-compilation support similar to linux on windows)

please test that it builds and runs correctly

**Comment by Steveice10** [comment]
Few things:
* I now have to do `dotnet workload install macos` to build at all, where as before I could build without that just fine.
* Rider refuses to run the project unless `.net8.0-macos` is changed to `.net8.0` and `OutputType = Library` is removed ('Error: Project has no runnable target frameworks defined').
* Publish script also does not work properly without the above; it outputs a DLL file which can't be ran, and if I change just the `OutputType` and not the target framework it does not build.
* Does not work with the delegate types removed, get this error: `System.ArgumentException: The specified Type must not be a generic type. (Parameter 'delegate')`.

This diff fixes the issues for me:
```diff
diff --git a/Ps3DiscDumper/Utils/MacOS/DiskArbitration.cs b/Ps3DiscDumper/Utils/MacOS/DiskArbitration.cs
index 491e06a..2df6f62 100644
--- a/Ps3DiscDumper/Utils/MacOS/DiskArbitration.cs
+++ b/Ps3DiscDumper/Utils/MacOS/DiskArbitration.cs
@@ -12,6 +12,9 @@ public static partial class DiskArbitration
 
     public static readonly IntPtr DescriptionMediaKindKey = CoreFoundation.__CFStringMakeConstantString("DAMediaKind");
 
+    public delegate void DADiskAppearedCallback(IntPtr disk, IntPtr context);
+    public delegate void DADiskDisappearedCallback(IntPtr disk, IntPtr context);
+
     [LibraryImport(LibraryName), UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
     public static partial IntPtr DASessionCreate(IntPtr allocator);
 
diff --git a/UI.Avalonia/UI.Avalonia.csproj b/UI.Avalonia/UI.Avalonia.csproj
index 68102b6..47afed7 100644
--- a/UI.Avalonia/UI.Avalonia.csproj
+++ b/UI.Avalonia/UI.Avalonia.csproj
@@ -1,6 +1,5 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
     <PropertyGroup>
-        <OutputType>WinExe</OutputType>
         <Nullable>enable</Nullable>
         <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
         <ApplicationManifest>app.manifest</ApplicationManifest>
@@ -17,19 +16,21 @@
         <TargetFramework>net8.0-windows</TargetFramework>
         <RuntimeIdentifier>win-x64</RuntimeIdentifier>
         <DefineConstants>WINDOWS</DefineConstants>
+        <OutputType>WinExe</OutputType>
     </PropertyGroup>
 
     <PropertyGroup Condition="'$(Configuration)' == 'Linux'">
         <TargetFramework>net8.0</TargetFramework>
         <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
         <DefineConstants>LINUX</DefineConstants>
+        <OutputType>Exe</OutputType>
     </PropertyGroup>
 
     <PropertyGroup Condition="'$(Configuration)' == 'MacOS'">
-        <TargetFramework>net8.0-macos</TargetFramework>
+        <TargetFramework>net8.0</TargetFramework>
         <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
         <DefineConstants>MACOS</DefineConstants>
-        <OutputType>Library</OutputType>
+        <OutputType>Exe</OutputType>
     </PropertyGroup>
 
     <PropertyGroup Condition="'$(Configuration)'!='Debug'">
diff --git a/UI.Avalonia/Views/MainWindow.axaml.macos.cs b/UI.Avalonia/Views/MainWindow.axaml.macos.cs
index c46bb9a..26d2bdf 100644
--- a/UI.Avalonia/Views/MainWindow.axaml.macos.cs
+++ b/UI.Avalonia/Views/MainWindow.axaml.macos.cs
@@ -41,8 +41,10 @@ public partial class MainWindow
         {
             runLoop = CF.CFRunLoopGetCurrent();
 
-            var diskAppearedDelegatePtr = Marshal.GetFunctionPointerForDelegate(DiskAppeared);
-            var diskDisappearedDelegatePtr = Marshal.GetFunctionPointerForDelegate(DiskDisappeared);
+            var diskAppearedDelegate = new DiskArbitration.DADiskAppearedCallback(DiskAppeared);
+            var diskDisappearedDelegate = new DiskArbitration.DADiskDisappearedCallback(DiskDisappeared);
+            var diskAppearedDelegatePtr = Marshal.GetFunctionPointerForDelegate(diskAppearedDelegate);
+            var diskDisappearedDelegatePtr = Marshal.GetFunctionPointerForDelegate(diskDisappearedDelegate);
 
             var cfAllocator = CF.CFAllocatorGetDefault();
             var daSession = DiskArbitration.DASessionCreate(cfAllocator);
diff --git a/publish-mac.ps1 b/publish-mac.ps1
index 73e918a..6b9b0ee 100644
--- a/publish-mac.ps1
+++ b/publish-mac.ps1
@@ -19,7 +19,7 @@ if (-not $IsMacOS)
 }
 
 Write-Host 'Building macOS binary...' -ForegroundColor Cyan
-dotnet publish -v:q -r osx-arm64 -f net8.0-macos --self-contained -c MacOS -o distrib/gui/mac/ UI.Avalonia/UI.Avalonia.csproj /p:PublishTrimmed=False /p:PublishSingleFile=True
+dotnet publish -v:q -r osx-arm64 -f net8.0 --self-contained -c MacOS -o distrib/gui/mac/ UI.Avalonia/UI.Avalonia.csproj /p:PublishTrimmed=False /p:PublishSingleFile=True
 if (($LASTEXITCODE -eq 0) -and ($IsMacOS -or ($PSVersionTable.Platform -eq 'Unix')))
 {
     chmod +x distrib/gui/mac/ps3-disc-dumper
```

**Comment by 13xforever** [comment]
Can you pull and test again with these changes?

**Comment by 13xforever** [comment]
And another commit that may or may not work, that's using native function pointers for interop callbacks

**Comment by Steveice10** [comment]
Yep it's working now. I've also rebased and figured out a way to get it to produce a nice bundled .app instead of loose executables and dylibs, and changed to `tar.gz` packaging as `zip` does not preserve the executable bit on the executable file.

**Comment by 13xforever** [comment]
Sweet. Can you test one more commit? I'd prefer not to use StringBuilder in interop if we can.

**Comment by Steveice10** [comment]
There was one issue with adding 1 to the length which was wrong ("Null character in path" error). I've fixed that and it works.

**Comment by 13xforever** [comment]
Yeah, idk why I thought '\0' may be required, but I also fixed the index check as it returns -1 if nothing was found

**Comment by 13xforever** [comment]
Let me tinker with publish scripts so I can build on windows and I think it'll be good to go

**Comment by Steveice10** [comment]
> Let me tinker with publish scripts so I can build on windows and I think it'll be good to go

You may run into issues where macOS ARM apps have to be signed in some way, even with an ad-hoc signature, which is done by .NET with the macOS `codesign` tool. Worth a check to see if it just works but the resulting app may not run.

Could be resolved with something like a GitHub Actions workflow for building releases.

**Comment by 13xforever** [comment]
I'll see what I can do with github actions to automate release publishing
Here's the result from local windows build that probably won't work: https://1drv.ms/u/s!AruI8iDXabVJgaA1577Lm3J3njqxOQ?e=gxjLaK

**Comment by Steveice10** [comment]
> I'll see what I can do with github actions to automate release publishing Here's the result from local windows build that probably won't work: https://1drv.ms/u/s!AruI8iDXabVJgaA1577Lm3J3njqxOQ?e=gxjLaK

Yeah it doesn't run from there, outside of the signature stuff I think the Windows filesystem also might be clobbering some of the necessary file attributes.

**Comment by 13xforever** [comment]
Thank you for sticking with this pr, I'll see about setting up github actions asap (probably next weekend)

**Comment by Steveice10** [comment]
I'll see if I can throw something basic together for that as well, should be fairly straightforward to make a workflow that produces and uploads the publishing bundles for each platform.

**Comment by 13xforever** [comment]
Nah, I need some specific workflow and I have some experience with gh actions

**Pull request merged**
